
apiVersion: v1
kind: Template
metadata:
  name: helloworld
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      generation: 1
      labels:
        app: helloworld
      name: helloworld-${STAGE}
    spec:
      replicas: 1
      selector:
        app: helloworld
        deploymentconfig: helloworld-${STAGE}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: helloworld
            deploymentconfig: helloworld-${STAGE}
        spec:
          containers:
          - image: 1docker-registry.default.svc:5000/${PROJECT_NAME}/helloworld:latest
            imagePullPolicy: Always
            name: helloworld-${STAGE}
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: helloworld
      name: helloworld-${STAGE}
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        deploymentconfig: helloworld-${STAGE}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      name: helloworld-${STAGE}
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: helloworld-${STAGE}
        weight: 100
      wildcardPolicy: None

parameters:
- name: STAGE
  value: devl
- name: PROJECT_NAME
  VALUE: rha-example
