apiVersion: v1
kind: BuildConfig
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  source:
    type: Git
    git:
      ref: master
      uri: 'https://github.com/iptrha/handson_erfa_openshift.git'
    contextDir: 2_helloworld
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-openjdk:latest
  output:
    to:
      kind: ImageStreamTag
      name: helloworld:latest
  resources: {}
