
apiVersion: v1
kind: Template
metadata:
  name: redis-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      generation: 1
      labels:
        app: helloworld
      name: helloworld-${STAGE}
    spec:
      replicas: 1
      selector:
        app: helloworld
        deploymentconfig: helloworld-${STAGE}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: helloworld
            deploymentconfig: helloworld-${STAGE}
        spec:
          containers:
          - image: helloworld:latest
            imagePullPolicy: Always
            name: helloworld
            ports:
            - containerPort: 8080
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status: {}
parameters:
- name: STAGE
  value: devl
