kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "helloworld-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/iptrha/handson_erfa_openshift.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: 2_helloworld/jenkins/Jenkinsfile
